Database models
Grace-Shopper-E/grace-shopper pull request #51
Opened 2022-11-08 22:47 UTC by Lauren-Baca

Order and User models updated and done (for now)

2022-11-08 23:08 UTC, christine-zheng requested changes
For User model, i suggest:
- password should also be allowNull false and validate notEmpty
- add email attribute: should be unique and validate that it is email format

2022-11-09 15:15 UTC, Lauren-Baca commented
Implemented suggested changes.

2022-11-09 16:56 UTC, alliebug commented
can we maybe prioritize this?

2022-11-09 17:32 UTC, siyunfeng approved these changes

2022-11-09 17:33 UTC, christine-zheng approved these changes

2022-11-09 17:33 UTC, merged